### ISSUE TITLE
Fuzzer doesn't account for the fact that Bun and Deno ignore message bodies in `GET` requests.

### ISSUE THREAD

**Issue by kenballus** [narfindustries/http-garden#22]
This could use a normalization

**Comment by gstrauss** [comment]
Related: lighttpd by default will reject GET with request body with 400 Bad Request unless lighttpd.conf is explicitly configured to permit GET with request body: `server.http-parseopts += ("method-get-body" => "enable")`
Reference: lighttpd [server.http-parseopts](https://wiki.lighttpd.net/Server_http-parseoptsDetails) documentation

**Comment by kenballus** [comment]
I had noticed this, but didn't see that option. I will enable that in the Lighttpd config. Thanks!

**Comment by AcnoSaga** [comment]
We neither have Bun or Deno in the project anymore. Should close this.

**Comment by kenballus** [comment]
yep :)
