### ISSUE TITLE
Grid view not accurate

### ISSUE THREAD

**Issue by tstOutpost24** [narfindustries/http-garden#31]
In [this](https://github.com/narfindustries/http-garden/commit/e3fe86b44620de9fa9ce8aefd292d532977b68ae) commit there may be a typo in the comparison between j and i. Perhaps I am misunderstanding the intent behind this code, but it causes the grid view not to work in "both" directions? 

When the line 101 = `if j <=i:`
![j is less than or equal to i](https://github.com/narfindustries/http-garden/assets/68554538/baef9398-14be-4d71-b405-113efa3ad224)

When the line 101 = `if j == i:`
![j is equal to i](https://github.com/narfindustries/http-garden/assets/68554538/88e8cf29-441f-4ee7-ab21-c89532b1ab77)

Payload was set to "payload 'POST / HTTP/1.1\r\nHost: a\r\nTransfer-Encoding: chunked\r\n\r\n0\n\r\n'"

\\Tom

**Comment by kenballus** [comment]
Yeah; I probably should have documented that change :)

I got rid of the duplicated entries because they cluttered the view.

**Comment by kenballus** [comment]
In other words, this is intentional. I'm going to close this issue and update the README to match the current output from `grid`.

**Comment by kenballus** [comment]
I'm having difficulty understanding the meaning of the arrow characters in that output.

I'd be interested in seeing your local changes :)
