### ISSUE TITLE
Re-add Bun

### ISSUE THREAD

**Issue by kenballus** [narfindustries/http-garden#40]

**Comment by kenballus** [comment]
Uses picohttpparser, which we already have through h2o

**Comment by DemiMarie** [comment]
It might use it differently 🙂.

**Comment by kenballus** [comment]
It totally does! See https://github.com/oven-sh/bun/issues/8893 and https://github.com/oven-sh/bun/issues/8648

My impression is that the Bun maintainers have enough to do right now, and aren't so interested in fixing these kinds of parsing bugs. Afaict, their picohttpparser is way out of date, too.

At the end of the day, we lean conservative on adding new targets to the Garden; especially big targets like Bun with long build times. Maybe we should loosen up about this.
