### ISSUE TITLE
Request for details/documentation on google_classic setup - reproduction issues

### ISSUE THREAD

**Issue by JeppW** [narfindustries/http-garden#67]
I'm unable to reproduce the behaviour of `google_classic` in http-garden in a live Google Cloud environment. Specifically, my live load balancer performs normalizations and various transformations that do not happen in http-garden (such as combining multiple small chunks into a single larger one) before forwarding it to my VM. 

Currently, I have an e2-micro VM behind a "Classic application load balancer (HTTP/HTTPS, external, global workloads)" with CDN enabled. 

Could you share some details of the setup behind `google_classic` or perhaps even add some documentation of the configuration of all the external services? That would be very helpful for building PoCs and testing ideas in real-world settings.

Amazing project by the way!

**Comment by kenballus** [comment]
> Amazing project by the way!

Thanks!

> Currently, I have an e2-micro VM behind a "Classic application load balancer (HTTP/HTTPS, external, global workloads)" with CDN enabled.

This sounds right.

> Could you share some details of the setup behind google_classic or perhaps even add some documentation of the configuration of all the external services? That would be very helpful for building PoCs and testing ideas in real-world settings.

> I'm unable to reproduce the behaviour of google_classic in http-garden in a live Google Cloud environment. Specifically, my live load balancer performs normalizations and various transformations that do not happen in http-garden (such as combining multiple small chunks into a single larger one) before forwarding it to my VM.

That's interesting; presumably we have different configuration for our load balancers. I should probably have better documentation for the different configs of cloud services like this.

Anyway, here's a screenshot of the configuration I have for Classic App LB. If your config behaves differently, we should probably add that to the Garden as well, so it'd be nice if you could respond with your config :)

![image](https://github.com/user-attachments/assets/1f8b1fe7-926a-484a-b099-df6aedfc4a2b)

I currently have the CDN disabled, but I have periodically enabled it for testing cache poisoning vulns.

**Comment by JeppW** [comment]
Ah, I see! I had my LB configured with an instance group instead of a network endpoint group. Honestly, I'm not very familiar with Google Cloud, so I am not sure what exactly either of those mean. Anyway, I got it working, so thank you!
